version: 2
defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-28-alpha
  environment:
    JVM_OPTS: -Xmx3200m
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - jars-{{ checksum "build.gradle" }}-{{ checksum  "core/build.gradle" }}
            - jars
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: build sample
          command: ./gradlew build -PpreDexLibraries=false
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "core/build.gradle" }}
  check:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - checkJars-{{ checksum "build.gradle" }}-{{ checksum  "core/build.gradle" }}
            - checkJars
      - run:
          name: Run Check
          command: ./gradlew check -PpreDexLibraries=false
      - save_cache:
          paths:
            - ~/.gradle
          key: checkJars-{{ checksum "build.gradle" }}-{{ checksum  "core/build.gradle" }}
      - store_artifacts:
          path: core/build/reports
          destination: reports-core
      - store_artifacts:
          path: androidsample/build/reports
          destination: reports-sample
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: androidsample/build/test-results
#Workflows
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - check